/* GENERATED by makeglobal.py - edit the source, not this. */
window.LAW=(function(){
// ==============================================================================================
// laws.js - the Laws of the Game as plain data and plain functions
// Copyright (c) AI2ORBIT Co. 2026
//
// WHY THIS IS A SEPARATE FILE, WITH NOTHING GRAPHICAL IN IT
//
// If this project is handed to a games studio in September they will bring their own renderer,
// and everything tied to the renderer will be thrown away. What survives a change of engine is
// the rules and the data model. So the rules live here: no three.js, no DOM, no canvas, no
// import of anything at all. This module runs unchanged in a browser, under node, and inside
// somebody else's engine. It is tested under node with no browser present, which is the proof
// that it is portable rather than the claim.
//
// Every function is PURE. It is handed a description of the world and returns a decision. It
// never moves a player, never writes to the screen and never keeps a secret. A referee decision
// that cannot be reproduced from the same inputs is not a rule, it is a mood.
//
// WHERE THE NUMBERS COME FROM, AND WHERE THEY DO NOT
//
// The distances are the Laws of the Game as published by the IFAB: 9.15 m at a free kick and a
// corner, 11 m for the penalty mark, a 9.15 m penalty arc, a 1 m corner arc, 4 m at a dropped
// ball, six seconds for a goalkeeper holding the ball, a 16.5 m by 40.3 m penalty area and a
// 5.5 m by 18.32 m goal area.
//
// The WORDS in the comments are my own summary of each Law and are not quoted text. Where a Law
// leaves something to the referee - "a few seconds" of advantage, what counts as clearly
// impacting an opponent - there is no number to copy, so this file invents one, and every such
// number is marked DECISION with the reason beside it. A decision printed as though it were a
// Law is the commonest way a rules engine misleads the person reading its output.
//
// Anything I could not source is marked NOT STATED rather than guessed at.
// ==============================================================================================

// ---------------------------------------------------------------------------------- geometry
//
// Coordinates. x runs along the length of the pitch, from -halfLength to +halfLength, and the
// halfway line is x = 0. z runs across the width. A team's `dir` is +1 if it attacks +x and -1
// if it attacks -x, so `x * dir` is always "how far towards the goal being attacked", which
// removes every left/right special case from the offside code below.

const PITCH = {
  halfLength: 52.5,            // 105 m long, the middle of the Law 1 range
  halfWidth: 34,               // 68 m wide
  goalHalfWidth: 3.66,         // 7.32 m between the posts
  crossbar: 2.44,              // 2.44 m to the underside of the bar
  penaltyAreaDepth: 16.5,
  penaltyAreaHalfWidth: 20.15, // 40.3 m across
  goalAreaDepth: 5.5,
  goalAreaHalfWidth: 9.15,     // 18.32 m across
  penaltyMarkFromGoal: 11,
  penaltyArcRadius: 9.15,
  cornerArcRadius: 1,
  ballRadius: 0.11,            // a size 5 ball is 0.22 m across
  lineWidth: 0.12,
};

// The numbers a competition is allowed to move sit here rather than being typed into the code,
// because a profile per competition is the seam that lets UEFA, FIFA and the rest differ from
// each other without any of them forking a rule. Week 2 built that layer: profiles.js resolves
// a competition into an object shaped exactly like this one, and hands it to the functions
// below as their `laws` argument. Nothing in this file knows profiles.js exists, and it must
// stay that way - the moment a rule here branches on a competition name, the seam is gone.
const LAWS = {
  freeKickDistance: 9.15,
  cornerKickDistance: 9.15,
  droppedBallSeparation: 4,
  wallAttackerGap: 1,          // an attacker must stay 1 m from a wall of three or more
  goalkeeperSeconds: 6,

  // DECISION, not a Law. The Law says a player level with the second last opponent is NOT
  // offside, and states no tolerance. Positions here are point masses, so a strict comparison
  // makes a player offside by a millimetre. Zero is the Law; a competition running semi
  // automated offside publishes its own, and profiles.js sets it without touching this file.
  levelToleranceM: 0,

  // DECISION, not a Law. The Law says the referee allows play to continue for "a few seconds".
  // Four is inside every reading of that phrase I can defend and is not copied from anywhere.
  advantageSeconds: 4,

  // DECISION, not a Law. "Interfering with an opponent" is a judgement in the Law and a
  // distance here. 2 m is close enough to challenge; the vision cone below is the other half.
  clearImpactM: 2.0,
  visionConeDeg: 14,
};

const RESTART = {
  KICK_OFF:   'kickOff',
  THROW_IN:   'throwIn',
  GOAL_KICK:  'goalKick',
  CORNER:     'cornerKick',
  DIRECT:     'directFreeKick',
  INDIRECT:   'indirectFreeKick',
  PENALTY:    'penaltyKick',
  DROPPED:    'droppedBall',
};

// A goal cannot be scored DIRECTLY from these. From the others it can.
const NO_DIRECT_GOAL = new Set([RESTART.THROW_IN, RESTART.INDIRECT, RESTART.DROPPED]);
function canScoreDirectly(restartType){ return !NO_DIRECT_GOAL.has(restartType); }

// Law 11: there is no offside offence from these three. Note that a dropped ball and a free
// kick are NOT on the list - offside applies from those.
const NO_OFFSIDE_FROM = new Set([RESTART.THROW_IN, RESTART.GOAL_KICK, RESTART.CORNER]);
function offsideAppliesFrom(restartType){ return !NO_OFFSIDE_FROM.has(restartType); }

function inPenaltyArea(x, z, dir, pitch = PITCH){
  // The penalty area DEFENDED by a team whose attacking direction is dir sits at -dir.
  return x * dir <= -(pitch.halfLength - pitch.penaltyAreaDepth)
      && x * dir >= -pitch.halfLength
      && Math.abs(z) <= pitch.penaltyAreaHalfWidth;
}

function inGoalArea(x, z, dir, pitch = PITCH){
  return x * dir <= -(pitch.halfLength - pitch.goalAreaDepth)
      && x * dir >= -pitch.halfLength
      && Math.abs(z) <= pitch.goalAreaHalfWidth;
}

function penaltyMark(dir, pitch = PITCH){
  // The mark in front of the goal DEFENDED at -dir.
  return { x: -dir * (pitch.halfLength - pitch.penaltyMarkFromGoal), z: 0 };
}

// ---------------------------------------------------------------------------------- Law 9
//
// BALL IN AND OUT OF PLAY. The ball is out only when the WHOLE of it has passed over the whole
// of the line, on the ground or in the air. The first version of this game tested the CENTRE of
// the ball against the line, which puts the ball out half a ball early and, on a shot along the
// ground beside the post, decides a goal that a referee would not give. The ball's radius is in
// the test now.
//
// STATED ASSUMPTION: halfWidth and halfLength here are taken to the OUTER edge of the line, and
// the line belongs to the field, so the ball is out when its near face has cleared that edge.

function ballIsOut(x, z, pitch = PITCH){
  const r = pitch.ballRadius;
  return Math.abs(z) - r > pitch.halfWidth || Math.abs(x) - r > pitch.halfLength;
}

// The goal itself. Handed the ball's position before and after a step, this interpolates the
// crossing rather than sampling it, so the answer does not depend on the frame rate. The whole
// ball must pass over the whole line, so the crossing plane is the far side of the ball.
function goalCrossing(prev, now, pitch = PITCH){
  const r = pitch.ballRadius;
  for (const s of [-1, 1]) {
    const plane = s * (pitch.halfLength + r);      // whole ball over the whole line
    const wasBefore = (prev.x - plane) * s < 0;
    const isAfter   = (now.x  - plane) * s >= 0;
    if (!(wasBefore && isAfter)) continue;
    const dx = now.x - prev.x;
    const t  = Math.abs(dx) < 1e-9 ? 0 : (plane - prev.x) / dx;
    const z  = prev.z + (now.z - prev.z) * t;
    const y  = prev.y + (now.y - prev.y) * t;
    // The posts and the bar are the INSIDE edges of the goal, so the ball is in when its centre
    // is inside them by less than its own radius on either side.
    const inside = Math.abs(z) < pitch.goalHalfWidth - r && y < pitch.crossbar - r && y >= 0;
    return { crossed: true, side: s, z, y, t, goal: inside };
  }
  return { crossed: false, goal: false };
}

// ---------------------------------------------------------------------------------- Law 15/16/17
//
// WHAT THE RESTART IS WHEN THE BALL LEAVES THE FIELD.
//
//   over a touchline                    throw in to the opponents of the last touch
//   over a goal line, last touched by
//     an attacker                       goal kick
//     a defender                        corner kick
//
// "Attacker" and "defender" are relative to the goal line it went over, not to who is winning.

function restartForOut({ x, z, lastTouchTeam, lastTouchDir, pitch = PITCH }){
  const r = pitch.ballRadius;
  if (Math.abs(z) - r > pitch.halfWidth) {
    const side = Math.sign(z) || 1;
    return {
      type: RESTART.THROW_IN,
      team: lastTouchTeam === null || lastTouchTeam === undefined ? 0 : 1 - lastTouchTeam,
      // Taken from the point it crossed, so the x is kept and the z is put back on the line.
      x: Math.max(-pitch.halfLength, Math.min(pitch.halfLength, x)),
      z: side * pitch.halfWidth,
      reason: 'the whole ball passed over the touchline',
    };
  }
  if (Math.abs(x) - r > pitch.halfLength) {
    const side = Math.sign(x) || 1;            // which goal line it went over
    // The team that DEFENDS this line is the one whose dir points away from it.
    const defendingTeamAttacksAway = -side;
    const lastTouchWasDefender = lastTouchDir === defendingTeamAttacksAway;
    if (lastTouchWasDefender) {
      return {
        type: RESTART.CORNER,
        team: lastTouchTeam === null || lastTouchTeam === undefined ? 0 : 1 - lastTouchTeam,
        x: side * pitch.halfLength,
        z: (Math.sign(z) || 1) * pitch.halfWidth,
        reason: 'the whole ball passed over the goal line, last touched by a defender',
      };
    }
    return {
      type: RESTART.GOAL_KICK,
      team: lastTouchTeam === null || lastTouchTeam === undefined ? 0 : 1 - lastTouchTeam,
      // Anywhere in the goal area. The centre of it is a defensible default and is a DECISION.
      x: side * (pitch.halfLength - pitch.goalAreaDepth * 0.5),
      z: 0,
      reason: 'the whole ball passed over the goal line, last touched by an attacker',
    };
  }
  return { type: null, reason: 'the ball is still in play' };
}

// The corner arc: the ball is placed inside a quarter circle of 1 m at the corner flag.
function cornerSpot(sideX, sideZ, pitch = PITCH){
  return { x: sideX * (pitch.halfLength - 0.12), z: sideZ * (pitch.halfWidth - 0.12) };
}

// ---------------------------------------------------------------------------------- Law 11
//
// OFFSIDE, AS A DECISION IN THREE PARTS, WHICH IS HOW IT IS ACTUALLY REFEREED
//
//   1. POSITION, frozen at the moment a team mate PLAYS the ball, never when it arrives. A
//      player is in an offside position if any part of the head, body or feet is in the
//      opponents' half AND nearer to the opponents' goal line than BOTH the ball AND the
//      second last opponent. Level with either is NOT offside. The arms and hands do not count,
//      which this model cannot represent - see NOT STATED below.
//
//   2. INVOLVEMENT, judged when the ball is next played. Being in an offside position is not an
//      offence. It becomes one only by interfering with play, interfering with an opponent, or
//      gaining an advantage from a rebound or a deliberate save.
//
//   3. THE AWARD: an indirect free kick where the offence happened, including in the offending
//      player's own half.
//
// NOT STATED: this model carries one point per player, so it cannot tell a shoulder from a hand
// and it cannot apply the "only the parts that can score" clause. Every offside decision below
// is therefore taken on the player's CENTRE, and the margin in metres is returned beside every
// verdict so a caller can see how close the call was rather than being handed a bare yes.

function offsideLine({ opponents, ballX, dir, pitch = PITCH, laws = LAWS }){
  // Every opponent still on the field, measured towards the goal being attacked.
  const proj = opponents.filter(o => o.on !== false).map(o => o.x * dir).sort((a, b) => b - a);
  // "The second last opponent" counts the goalkeeper. A keeper who has come out is the reason
  // this must never be written as "the last defender".
  const secondLast = proj.length >= 2 ? proj[1]
                   : proj.length === 1 ? proj[0]
                   : -pitch.halfLength;
  const ballProj = ballX * dir;
  // Beyond ALL THREE: the ball, the second last opponent, and the halfway line. "Beyond all
  // three" is the LARGEST of them, not the smallest.
  //
  // The first version of this line wrote Math.min, and every check that only asked "is a player
  // 35 m up the pitch offside" still passed, because with the minimum the line collapsed onto
  // the halfway line and nearly everybody in the opponents' half came back offside. It was the
  // check for the player who is past the ball but BEHIND the defence - onside, and the whole
  // point of the word "both" in the Law - that failed. A rule tested only where it says yes is
  // a rule that cannot fail its own test.
  const limit = Math.max(secondLast, ballProj, 0);
  return { limitProj: limit, secondLastProj: secondLast, ballProj, dir,
           x: limit * dir, tolerance: laws.levelToleranceM };
}

function inOffsidePosition(player, line, laws = LAWS){
  const proj = player.x * line.dir;
  const margin = proj - line.limitProj;          // positive means beyond the line
  return { offside: margin > laws.levelToleranceM, marginM: +margin.toFixed(4),
           beyondBall: proj > line.ballProj, beyondSecondLast: proj > line.secondLastProj,
           inOpponentHalf: proj > 0 };
}

// Step 1: freeze the picture at the moment the ball is played.
function snapshotOffside({ attackers, opponents, ballX, dir, restartType,
                                  pitch = PITCH, laws = LAWS }){
  const applies = offsideAppliesFrom(restartType || null);
  const line = offsideLine({ opponents, ballX, dir, pitch, laws });
  const flagged = [];
  if (applies) {
    for (const a of attackers) {
      if (a.on === false) continue;
      const v = inOffsidePosition(a, line, laws);
      if (v.offside) flagged.push({ id: a.id, marginM: v.marginM, x: a.x, z: a.z });
    }
  }
  return { line, flagged, applies, restartType: restartType || null,
           flaggedIds: new Set(flagged.map(f => f.id)) };
}

// Step 2: when the ball is next played, was one of those players involved?
//
// `contact` describes what happened: who touched it, whether the touch came off a post, the bar,
// an opponent or a deliberate save, and whether an opponent was deliberately playing the ball.
function offsideOffence(snapshot, contact, laws = LAWS){
  const none = { offence: false };
  if (!snapshot || !snapshot.applies || snapshot.flagged.length === 0) return none;

  const flagged = snapshot.flagged.find(f => f.id === contact.touchedBy);

  // A player who receives the ball directly from an opponent who DELIBERATELY played it is not
  // committing an offence - unless that deliberate play was a save. This is the clause that
  // stops a defender's clearance putting his own opponent offside.
  if (contact.fromDeliberateOpponentPlay && !contact.fromSave)
    return { offence: false, reason: 'received from an opponent who deliberately played it' };

  if (flagged) {
    if (contact.fromRebound || contact.fromSave)
      return { offence: true, kind: 'gaining an advantage', id: flagged.id,
               marginM: flagged.marginM,
               reason: contact.fromSave ? 'played the ball after a deliberate save'
                                        : 'played the ball after a rebound' };
    return { offence: true, kind: 'interfering with play', id: flagged.id,
             marginM: flagged.marginM, reason: 'played or touched the ball' };
  }

  // Interfering with an OPPONENT, without touching the ball at all. Two tests, both stated as
  // decisions above: standing in the goalkeeper's line of sight, or close enough to an opponent
  // who is trying to play it that the opponent is clearly impacted.
  for (const f of snapshot.flagged) {
    if (contact.blockedVisionOf && contact.blockedVisionOf === f.id)
      return { offence: true, kind: 'interfering with an opponent', id: f.id,
               marginM: f.marginM, reason: 'obstructed the line of vision' };
    if (contact.challengedBy && contact.challengedBy === f.id)
      return { offence: true, kind: 'interfering with an opponent', id: f.id,
               marginM: f.marginM, reason: 'challenged an opponent for the ball' };
  }
  return none;
}

// Is a player standing in the keeper's line of sight to the ball? Cone test, both ends checked:
// the player must be BETWEEN the keeper and the ball, not merely in the same direction.
function blocksVision({ player, keeper, ball, laws = LAWS }){
  const kx = ball.x - keeper.x, kz = ball.z - keeper.z;
  const px = player.x - keeper.x, pz = player.z - keeper.z;
  const kl = Math.hypot(kx, kz), pl = Math.hypot(px, pz);
  if (kl < 1e-6 || pl < 1e-6) return false;
  if (pl > kl) return false;                                  // behind the ball, not in the way
  const cos = (kx * px + kz * pz) / (kl * pl);
  const ang = Math.acos(Math.max(-1, Math.min(1, cos))) * 180 / Math.PI;
  return ang <= laws.visionConeDeg;
}

// ---------------------------------------------------------------------------------- Law 12
//
// FOULS. The Law splits them by what the restart is, not by how bad they look.
//
//   DIRECT free kick: charging, jumping at, kicking, pushing, striking, tackling or challenging,
//                     tripping, holding, impeding WITH contact, biting, spitting, throwing
//                     something at the ball, and handling the ball deliberately.
//   INDIRECT free kick: playing dangerously, impeding WITHOUT contact, dissent, holding the ball
//                     more than six seconds as goalkeeper, handling after a deliberate kick or
//                     throw in from a team mate, and a second touch at a restart.
//
// A direct free kick offence by a defender INSIDE their own penalty area is a penalty kick. An
// indirect free kick offence inside it stays an indirect free kick.

const DIRECT_OFFENCES = new Set(['charge','jump','kick','push','strike','tackle','trip','hold',
                                 'impedeContact','handball','throwObject','bite','spit']);
const INDIRECT_OFFENCES = new Set(['dangerousPlay','impedeNoContact','dissent','sixSeconds',
                                   'backPass','secondTouch','offside','goalkeeperRelease']);

function offenceIsDirect(offence){ return DIRECT_OFFENCES.has(offence); }
function offenceIsIndirect(offence){ return INDIRECT_OFFENCES.has(offence); }

function foulRestart({ offence, x, z, offenderDir, offenderIsDefending,
                              pitch = PITCH }){
  const known = DIRECT_OFFENCES.has(offence) || INDIRECT_OFFENCES.has(offence);
  if (!known) return { type: null, reason: 'NOT STATED: no such offence in this model' };

  if (INDIRECT_OFFENCES.has(offence))
    return { type: RESTART.INDIRECT, x, z, offence,
             reason: 'an indirect free kick offence, wherever it happened' };

  // A direct free kick offence by a player defending, inside the area they defend.
  if (offenderIsDefending && inPenaltyArea(x, z, offenderDir, pitch)) {
    const mark = penaltyMark(offenderDir, pitch);
    return { type: RESTART.PENALTY, x: mark.x, z: mark.z, offence,
             reason: 'a direct free kick offence by a defender inside their own penalty area' };
  }
  return { type: RESTART.DIRECT, x, z, offence,
           reason: 'a direct free kick offence outside the penalty area' };
}

// ---------------------------------------------------------------------------------- advantage
//
// The referee lets play run if the team that was fouled keeps the ball and a promising attack
// is on. If the advantage does not come off within a few seconds, the original offence is
// brought back. This is a small state machine because the decision is made across time and not
// at a single instant, and writing it as a pure step keeps it testable with no clock.

function advantageOpen(t, foul){ return { openedAt: t, foul, resolved: null }; }

function advantagePoll(adv, t, world, laws = LAWS){
  if (!adv || adv.resolved) return adv;
  const elapsed = t - adv.openedAt;
  if (world.foulingTeamHasBall)
    return { ...adv, resolved: 'pullBack',
             reason: 'the ball went back to the offending side, so there was no advantage' };
  if (world.goalScored)
    return { ...adv, resolved: 'played', reason: 'the attack ended in a goal' };
  if (elapsed >= laws.advantageSeconds)
    return { ...adv, resolved: world.attackStillOn ? 'played' : 'pullBack',
             reason: world.attackStillOn ? 'the advantage came off'
                                         : 'the advantage did not come off in time' };
  return adv;                                     // still being held
}

// ---------------------------------------------------------------------------------- Law 13
//
// FREE KICKS. Opponents stay 9.15 m away until the ball is in play, which is when it is kicked
// and clearly moves. From an INDIRECT free kick a goal cannot be scored until a second player
// touches the ball; if it goes straight in, the restart is a goal kick, or a corner if it goes
// into the kicker's own goal.
//
// The wall. Where a wall of three or more defenders is formed, every attacker must stay at least
// 1 m from it until the ball is in play.

function wallFor({ ballX, ballZ, defendDir, count, pitch = PITCH, laws = LAWS }){
  const goalX = -defendDir * pitch.halfLength;
  let dx = goalX - ballX, dz = 0 - ballZ;
  const d = Math.hypot(dx, dz) || 1;
  dx /= d; dz /= d;
  const cx = ballX + dx * laws.freeKickDistance;
  const cz = ballZ + dz * laws.freeKickDistance;
  const px = -dz, pz = dx;                        // across the line of the kick
  const out = [];
  const spacing = 0.55;                           // shoulder to shoulder
  for (let i = 0; i < count; i++) {
    const off = (i - (count - 1) / 2) * spacing;
    out.push({ x: cx + px * off, z: cz + pz * off });
  }
  return { positions: out, distance: laws.freeKickDistance,
           attackerGap: count >= 3 ? laws.wallAttackerGap : 0 };
}

function freeKickLegal({ opponents, ballX, ballZ, laws = LAWS }){
  const tooClose = opponents.filter(o => o.on !== false &&
    Math.hypot(o.x - ballX, o.z - ballZ) < laws.freeKickDistance - 1e-9);
  return { legal: tooClose.length === 0, encroaching: tooClose.map(o => o.id),
           required: laws.freeKickDistance };
}

// ---------------------------------------------------------------------------------- Law 14
//
// THE PENALTY KICK. The ball is on the mark. The kicker is identified. The defending goalkeeper
// stays on the goal line, facing the kicker, with at least part of one foot touching or in line
// with it, until the ball is kicked. Everybody else is on the field, outside the penalty area,
// behind the penalty mark, and at least 9.15 m from it - which is exactly what the arc is for.

function penaltySetup({ defendDir, pitch = PITCH, laws = LAWS }){
  const mark = penaltyMark(defendDir, pitch);
  const goalX = -defendDir * pitch.halfLength;
  return {
    mark,
    keeperLine: { x: goalX, zRange: [-pitch.goalHalfWidth, pitch.goalHalfWidth] },
    // "Behind the ball" means further from the goal being attacked than the mark is.
    behindMarkX: mark.x,
    minimumFromMark: laws.penaltyArcRadius || pitch.penaltyArcRadius,
    // Behind the ball, which is away from the goal being attacked, so towards +defendDir.
    kickerRunUpFrom: { x: mark.x + defendDir * 3, z: 0 },
  };
}

function penaltyLegal({ others, defendDir, mark, pitch = PITCH }){
  const bad = [];
  for (const p of others) {
    if (p.on === false) continue;
    if (inPenaltyArea(p.x, p.z, defendDir, pitch)) { bad.push({ id: p.id, why: 'in the area' }); continue; }
    if (Math.hypot(p.x - mark.x, p.z - mark.z) < pitch.penaltyArcRadius - 1e-9) {
      bad.push({ id: p.id, why: 'inside the arc' }); continue;
    }
    // Behind the mark: nearer the halfway line than the mark is to the goal being attacked.
    const towardsGoal = (p.x - mark.x) * -defendDir;
    if (towardsGoal > 1e-9) bad.push({ id: p.id, why: 'ahead of the ball' });
  }
  return { legal: bad.length === 0, encroaching: bad };
}

// ---------------------------------------------------------------------------------- Law 8
//
// THE DROPPED BALL. Play restarts with a dropped ball when the referee stops play for a reason
// that is not an offence. Who it is dropped for is decided by WHERE, not by who deserves it:
//
//   the ball was in the penalty area, or play stopped there   -> dropped for the defending
//                                                                goalkeeper
//   anywhere else                                             -> dropped for one player of the
//                                                                team that last touched it, at
//                                                                the place it last touched a
//                                                                player, an outside agent or
//                                                                the ground
//
// Every other player stays 4 m away until the ball is in play, which is when it touches the
// ground. There is no offside exemption at a dropped ball: offside applies.

function droppedBall({ x, z, lastTouchTeam, lastTouchDir, teams, pitch = PITCH,
                              laws = LAWS }){
  for (const t of (teams || [])) {
    if (inPenaltyArea(x, z, t.dir, pitch)) {
      return { type: RESTART.DROPPED, team: t.team, toGoalkeeper: true,
               x, z, separation: laws.droppedBallSeparation,
               reason: 'play stopped inside a penalty area, so it is dropped for that keeper' };
    }
  }
  return { type: RESTART.DROPPED,
           team: lastTouchTeam === null || lastTouchTeam === undefined ? 0 : lastTouchTeam,
           toGoalkeeper: false, x, z, separation: laws.droppedBallSeparation,
           reason: 'dropped for the team that last touched it, where it last touched' };
}

// ---------------------------------------------------------------------------------- Law 12
//
// THE GOALKEEPER'S SIX SECONDS, and the back pass. A keeper may not control the ball with the
// hands for more than six seconds, and may not handle it at all after a team mate has
// deliberately kicked it to them or thrown it in to them. Both are indirect free kicks.

function goalkeeperHold(seconds, laws = LAWS){
  return { offence: seconds > laws.goalkeeperSeconds,
           restart: seconds > laws.goalkeeperSeconds ? RESTART.INDIRECT : null,
           allowed: laws.goalkeeperSeconds, held: +seconds.toFixed(2) };
}

function backPassOffence({ handled, lastTouchWasTeamMate, deliberateKick, fromThrowIn }){
  const offence = !!handled && !!lastTouchWasTeamMate && (!!deliberateKick || !!fromThrowIn);
  return { offence, restart: offence ? RESTART.INDIRECT : null,
           reason: offence ? 'the keeper handled a deliberate kick or throw in from a team mate'
                           : 'not a back pass offence' };
}

// ---------------------------------------------------------------------------------- summary
//
// A one line description of every restart, used by the on screen referee and by the tests, so
// the words the player reads and the words a check asserts on are the same string.

const RESTART_TEXT = {
  [RESTART.KICK_OFF]:  'KICK OFF',
  [RESTART.THROW_IN]:  'THROW IN',
  [RESTART.GOAL_KICK]: 'GOAL KICK',
  [RESTART.CORNER]:    'CORNER',
  [RESTART.DIRECT]:    'FREE KICK',
  [RESTART.INDIRECT]:  'INDIRECT FREE KICK',
  [RESTART.PENALTY]:   'PENALTY',
  [RESTART.DROPPED]:   'DROPPED BALL',
};

const LAWS_VERSION = 'week 1 - Laws 8, 9, 11, 12, 13, 14, 15, 16, 17';
// match.js carries the LAWS the MATCH is governed by (3, 5, 6, 7, 10 and the cards of 12) and
// profiles.js carries what each competition is allowed to change. Neither is imported here.

return {PITCH:PITCH,LAWS:LAWS,RESTART:RESTART,canScoreDirectly:canScoreDirectly,offsideAppliesFrom:offsideAppliesFrom,inPenaltyArea:inPenaltyArea,inGoalArea:inGoalArea,penaltyMark:penaltyMark,ballIsOut:ballIsOut,goalCrossing:goalCrossing,restartForOut:restartForOut,cornerSpot:cornerSpot,offsideLine:offsideLine,inOffsidePosition:inOffsidePosition,snapshotOffside:snapshotOffside,offsideOffence:offsideOffence,blocksVision:blocksVision,offenceIsDirect:offenceIsDirect,offenceIsIndirect:offenceIsIndirect,foulRestart:foulRestart,advantageOpen:advantageOpen,advantagePoll:advantagePoll,wallFor:wallFor,freeKickLegal:freeKickLegal,penaltySetup:penaltySetup,penaltyLegal:penaltyLegal,droppedBall:droppedBall,goalkeeperHold:goalkeeperHold,backPassOffence:backPassOffence,RESTART_TEXT:RESTART_TEXT,LAWS_VERSION:LAWS_VERSION};
})();
window.MATCH=(function(){
// ==============================================================================================
// match.js - the shape of a match: its periods, its officials, and how it is decided
// Copyright (c) AI2ORBIT Co. 2026
//
// Week 1 put the Laws that govern the BALL into laws.js - offside, fouls, restarts, the goal.
// This file is the other half: the Laws that govern the MATCH. Law 3 (the players and the
// substitutions), Law 5 (the referee), Law 6 (the other match officials, including the video
// assistant referee), Law 7 (the duration), Law 10 (how a winner is found), and the part of
// Law 12 that decides a card rather than a restart.
//
// Same discipline as laws.js and for the same reason: it imports nothing, it touches no DOM, no
// canvas and no three.js, every function is pure, and it is tested under node with no browser
// present. A studio that brings its own engine in September keeps this file unchanged.
//
// It imports laws.js for the pitch geometry ONLY, and nothing flows the other way. The
// dependency runs laws.js <- match.js <- profiles.js and never loops, so any one of the three
// can be read on its own.
//
// WHERE THE NUMBERS COME FROM
//
// The durations, the minimum of seven players, the fifteen minute interval, the four video
// review categories and the procedure for kicks from the penalty mark are the Laws of the Game
// as published by the IFAB. The WORDS are my own summary and are not quoted text.
//
// Almost everything else in a real match is not in the Laws at all - it is in the COMPETITION's
// own regulations, and the Laws say so explicitly ("competition rules must state..."). How many
// substitutes may be named, how many may be used, whether there is a video assistant referee,
// whether a drawn tie goes to extra time: none of that is a Law, and none of it is invented
// here. It is the profile layer's job, and profiles.js marks every one of those fields
// NOT STATED until a competition's published regulations fill it in.
//
// Anything decided by this file rather than by a Law is marked DECISION with the reason beside
// it. A decision printed as though it were a Law is the commonest way a rules engine misleads
// the person reading its output.
// ==============================================================================================

var {PITCH} = window.LAW;
// ---------------------------------------------------------------------------------- Law 7
//
// THE DURATION OF THE MATCH.
//
// Two equal halves of 45 minutes, which may be reduced only if that is agreed before the match
// and is in the competition rules. The half time interval is not more than 15 minutes. Where a
// competition requires extra time, it is two equal periods of 15 minutes.
//
// A half is never SHORTENED. If a penalty kick has to be taken or completed, the half is
// extended until it is finished, and that extension ends the moment the kick is over.

const PERIOD = {
  FIRST_HALF:     'firstHalf',
  SECOND_HALF:    'secondHalf',
  EXTRA_FIRST:    'extraFirst',
  EXTRA_SECOND:   'extraSecond',
  KICKS:          'kicksFromThePenaltyMark',
};

const DURATION = {
  halfMinutes: 45,
  halfTimeIntervalMaxMinutes: 15,
  extraTimeHalfMinutes: 15,
  // The Law provides for a drinks break of no more than one minute, and for cooling breaks,
  // which it puts at ninety seconds to three minutes. Both are only where the competition
  // permits them, so the profile layer decides whether they happen at all.
  drinksBreakMaxSeconds: 60,
  coolingBreakSeconds: [90, 180],
  // No interval between the two periods of extra time; the teams change ends and restart. There
  // IS a short interval before extra time begins, which the Law puts at no more than five
  // minutes and the competition may set.
  beforeExtraTimeMaxMinutes: 5,
};

// The reasons a period may be extended. This is the Law's own list, and it is a CLOSED list on
// purpose: an unrecognised reason is refused rather than quietly added, because a clock that
// accepts any excuse is a clock that cannot be audited afterwards.
const ADDED_TIME_REASONS = new Set([
  'substitution',
  'injuryAssessment',
  'injuryRemoval',
  'timeWasting',
  'disciplinarySanction',
  'medicalStoppage',        // drinks and cooling breaks, where the competition permits them
  'videoReview',            // both a check and a review at the pitchside monitor
  'goalCelebration',
  'otherSignificantDelay',
]);

// The fourth official indicates the MINIMUM additional time. The referee may add more than was
// indicated but never less, and that asymmetry is the whole point of the word minimum.
//
// DECISION, not a Law: the announced figure is rounded UP to the next whole minute. The Law
// gives no rounding rule. Rounding down would announce less time than was actually lost, which
// contradicts the one thing the Law does say about this number - that it is a minimum.
function addedTime(stoppages, opts = {}){
  let lost = 0;
  const rejected = [];
  for (const s of (stoppages || [])) {
    if (!ADDED_TIME_REASONS.has(s.reason)) { rejected.push(s.reason); continue; }
    lost += Math.max(0, s.seconds || 0);
  }
  const announced = Math.ceil(lost / 60);
  return {
    lostSeconds: lost,
    announcedMinutes: announced,
    // Named so a caller cannot mistake the announced figure for a limit.
    isMinimum: true,
    rejected,
    ok: rejected.length === 0,
    reason: rejected.length
      ? 'NOT STATED: these are not reasons the Law allows time for: ' + rejected.join(', ')
      : 'the sum of the stoppages, rounded up, announced as a minimum',
  };
}

// A period ends when its own time and the announced addition have run, UNLESS a penalty kick is
// still to be taken or completed - in which case it ends when that kick ends and not before.
function periodEnded({ elapsedSeconds, periodSeconds, addedSeconds = 0,
                              penaltyPending = false, penaltyComplete = false }){
  const past = elapsedSeconds >= periodSeconds + addedSeconds;
  if (!past) return { ended: false, reason: 'the period is still running' };
  if (penaltyPending && !penaltyComplete)
    return { ended: false, extended: true,
             reason: 'the period is extended for a penalty kick to be taken or completed' };
  return { ended: true, reason: penaltyComplete
    ? 'the period ended when the extended penalty kick was completed'
    : 'the period ran its time and its addition' };
}

// ---------------------------------------------------------------------------------- Law 3
//
// THE PLAYERS.
//
// Eleven a side, one of whom is the goalkeeper. A match may not START or CONTINUE if either team
// has fewer than seven players. Note both verbs: seven is not only a condition for kicking off.

const TEAM = {
  onField: 11,
  minimumToPlay: 7,
};

function teamCanPlay(playersOnField){
  return {
    ok: playersOnField >= TEAM.minimumToPlay,
    playersOnField,
    minimum: TEAM.minimumToPlay,
    reason: playersOnField >= TEAM.minimumToPlay
      ? 'the team has enough players'
      : 'a match may not start or continue with fewer than seven players in a team',
  };
}

// SUBSTITUTIONS.
//
// Every number here belongs to the competition, not to the Law, so this function takes them
// from the profile and states nothing itself. What it DOES own is the shape of the rules, which
// is the same everywhere:
//
//   - only a named substitute may come on
//   - a substituted player takes no further part, unless the competition permits return
//     substitutes (which the Law allows only in youth, veteran, disability and grassroots)
//   - the count of substitutions and the count of OPPORTUNITIES are two separate limits, and
//     the second is the one that is usually implemented wrongly
//   - a substitution made at half time, before extra time, or at half time in extra time does
//     NOT use an opportunity
//   - where the competition permits it, extra time carries one further substitution and one
//     further opportunity
//   - a concussion substitution, where the competition operates the protocol, is additional to
//     all of the above and does not use an opportunity
//
// `profile` is the resolved competition profile. A field it leaves NOT STATED is refused here
// rather than defaulted, because defaulting a competition's number is inventing it.

const NOT_STATED = '__NOT_STATED__';
function isStated(v){ return v !== NOT_STATED && v !== undefined; }

function substitutionCheck({ playerOffId, playerOnId, namedSubstitutes = [],
                                    substitutionsUsed = 0, opportunitiesUsed = 0,
                                    alreadySubstituted = [], atInterval = false,
                                    inExtraTime = false, concussion = false,
                                    simultaneousWithOpponent = false, profile }){
  const p = profile || {};
  const need = (k) => isStated(p[k]) ? p[k] : null;

  const missing = [];
  for (const k of ['substitutionsAllowed', 'substitutionOpportunities', 'returnSubstitutes'])
    if (need(k) === null) missing.push(k);
  if (concussion && need('concussionSubstitutes') === null) missing.push('concussionSubstitutes');
  if (inExtraTime) {
    for (const k of ['extraTimeExtraSubstitution', 'extraTimeExtraOpportunity'])
      if (need(k) === null) missing.push(k);
  }
  if (missing.length)
    return { allowed: false, notStated: missing,
             reason: 'NOT STATED in this profile: ' + missing.join(', ') +
                     '. The Law leaves these to the competition and none has been assumed.' };

  if (!namedSubstitutes.includes(playerOnId))
    return { allowed: false, reason: 'only a named substitute may take part' };

  if (alreadySubstituted.includes(playerOnId) && !p.returnSubstitutes)
    return { allowed: false,
             reason: 'a substituted player takes no further part in this competition' };

  if (concussion) {
    const used = p.concussionSubstitutionsUsed || 0;
    if (used >= p.concussionSubstitutes)
      return { allowed: false, reason: 'the concussion substitutions for this team are used up' };
    // A concussion substitution is permanent, is additional to the normal allowance, and does
    // not use an opportunity. The opposing team receives an additional substitution and an
    // additional opportunity, which is returned here so a caller cannot forget it.
    return { allowed: true, usesOpportunity: false, countsTowardsAllowance: false,
             opponentGains: { substitutions: 1, opportunities: 1 },
             reason: 'a concussion substitution, additional to the normal allowance' };
  }

  const allowance = p.substitutionsAllowed +
    (inExtraTime && p.extraTimeExtraSubstitution ? 1 : 0);
  if (substitutionsUsed >= allowance)
    return { allowed: false, used: substitutionsUsed, allowance,
             reason: 'the team has used all of its substitutions' };

  // The interval does not spend an opportunity. Nor does a substitution made before extra time
  // or at half time in extra time - all three are intervals, which is why one flag covers them.
  const usesOpportunity = !atInterval;
  const opportunities = p.substitutionOpportunities +
    (inExtraTime && p.extraTimeExtraOpportunity ? 1 : 0);
  if (usesOpportunity && opportunitiesUsed >= opportunities)
    return { allowed: false, opportunitiesUsed, opportunities,
             reason: 'the team has used all of its substitution opportunities' };

  return {
    allowed: true,
    usesOpportunity,
    countsTowardsAllowance: true,
    // Both teams substituting at the same stoppage spends ONE opportunity for each of them, not
    // one between them.
    opportunitySharedWithOpponent: !!simultaneousWithOpponent,
    playerOffId, playerOnId,
    reason: atInterval
      ? 'a substitution at an interval, which does not use an opportunity'
      : 'a substitution during play, which uses one of the opportunities',
  };
}

// Any of the players may change places with the goalkeeper, during a stoppage, with the referee
// told first. Doing it without telling the referee is a caution for both players.
function goalkeeperChange({ duringStoppage, refereeInformed }){
  const ok = !!duringStoppage && !!refereeInformed;
  return { allowed: ok,
           caution: duringStoppage && !refereeInformed ? ['playerOff', 'playerOn'] : [],
           reason: !duringStoppage ? 'a change of goalkeeper must wait for a stoppage'
                 : !refereeInformed ? 'the referee was not told, so both players are cautioned'
                 : 'a permitted change of goalkeeper' };
}

// ---------------------------------------------------------------------------------- Law 6
//
// THE MATCH OFFICIALS. The duties below are my own one line summaries, not quoted text, and
// they are the duties the Laws give rather than anything a broadcaster or a competition adds.

const OFFICIAL = {
  REFEREE:            'referee',
  ASSISTANT:          'assistantReferee',
  FOURTH:             'fourthOfficial',
  RESERVE_ASSISTANT:  'reserveAssistantReferee',
  VAR:                'videoAssistantReferee',
  AVAR:               'assistantVideoAssistantReferee',
};

const OFFICIAL_DUTIES = {
  [OFFICIAL.REFEREE]: [
    'enforces the Laws of the Game',
    'controls the match in cooperation with the other match officials',
    'acts as timekeeper and keeps a record of the match',
    'stops, suspends or abandons the match for any offence or outside interference',
    'takes disciplinary action, and allows play to continue when advantage is on',
    'stops play for a serious injury and allows play to continue for a slight one',
  ],
  [OFFICIAL.ASSISTANT]: [
    'indicates when the whole ball leaves the field, and which team restarts',
    'indicates when a player may be penalised for being in an offside position',
    'indicates when a substitution is requested',
    'at a penalty kick, indicates whether the goalkeeper moves off the goal line before the '
      + 'ball is kicked, and whether the ball crosses the line',
  ],
  [OFFICIAL.FOURTH]: [
    'assists with administrative duties before, during and after the match',
    'supervises the substitution procedure',
    'checks a replacement ball',
    'indicates the minimum additional time the referee intends to play',
    'reports irresponsible behaviour in the technical area to the referee',
  ],
  [OFFICIAL.RESERVE_ASSISTANT]: [
    'has one duty only: to replace an assistant referee or fourth official who cannot continue',
  ],
  [OFFICIAL.VAR]: [
    'assists the referee only for a clear and obvious error or a serious missed incident, and '
      + 'only in the four categories of decision listed below',
  ],
  [OFFICIAL.AVAR]: [
    'assists the video assistant referee, and watches the live play while a check is under way',
  ],
};

// The Law is explicit that only the REFEREE takes the decision, that other officials ADVISE, and
// that the referee's decisions on points of fact connected with play are final.
const DECISIONS_ARE_THE_REFEREES = true;

// ---------------------------------------------------------------------------------- Law 5
//
// CHANGING A DECISION.
//
// The referee may correct a restart decision on realising it was wrong, or on the advice of
// another official, but only while play has not restarted and the half has not ended with the
// referee off the field.
//
// There is a separate clause that catches people out: at the end of a half, if the referee is
// leaving the field to go to the review area or to send the players back out, an offence that
// happened before the half ended can STILL be sanctioned. The card survives even though the
// restart cannot be changed - so the two questions are answered separately here rather than
// being collapsed into one boolean.

function mayChangeRestart({ playRestarted, periodEnded: ended, refereeLeftField,
                                   matchTerminated }){
  if (playRestarted)
    return { may: false, reason: 'play has restarted, so the decision stands' };
  if (matchTerminated)
    return { may: false, reason: 'the match has been terminated' };
  if (ended && refereeLeftField)
    return { may: false,
             reason: 'the half ended and the referee has left the field of play' };
  return { may: true, reason: 'play has not restarted, so the decision may still be corrected' };
}

function mayStillSanction({ periodEnded: ended, refereeLeftField, goingToReviewArea,
                                   recallingPlayers, matchTerminated, offenceBeforeEnd = true }){
  if (matchTerminated)
    return { may: false, reason: 'the match has been terminated' };
  if (!ended) return { may: true, reason: 'the period is still running' };
  if (!offenceBeforeEnd)
    return { may: false, reason: 'the offence did not happen before the end of the period' };
  if (!refereeLeftField)
    return { may: true, reason: 'the referee has not left the field of play' };
  if (goingToReviewArea || recallingPlayers)
    return { may: true,
             reason: 'the referee left the field only to go to the review area or to recall '
                   + 'the players, so an offence before the end may still be sanctioned' };
  return { may: false, reason: 'the referee has left the field of play' };
}

// ---------------------------------------------------------------------------------- the VAR
//
// The video assistant referee may assist with FOUR categories of decision and no others, and
// then only for a clear and obvious error or a serious missed incident:
//
//   1. goal / no goal
//   2. penalty / no penalty
//   3. direct red card - NOT a second caution
//   4. mistaken identity, where the referee cautions or sends off the wrong player
//
// The exclusion of the second caution is the clause most often got wrong, so it is a separate
// branch here and has its own check in the suite. A second yellow card is not reviewable even
// though its consequence - a player sent off - is identical to a red.

const VAR_CATEGORY = {
  GOAL:     'goalOrNoGoal',
  PENALTY:  'penaltyOrNoPenalty',
  RED_CARD: 'directRedCard',
  IDENTITY: 'mistakenIdentity',
};

const VAR_CATEGORIES = new Set(Object.values(VAR_CATEGORY));

function varMayReview({ category, secondCaution = false, clearAndObviousError = false,
                               seriousMissedIncident = false, profile }){
  const p = profile || {};
  if (!isStated(p.videoAssistantReferee))
    return { review: false, notStated: ['videoAssistantReferee'],
             reason: 'NOT STATED in this profile: whether this competition operates a video '
                   + 'assistant referee. It is a competition decision, not a Law.' };
  if (!p.videoAssistantReferee)
    return { review: false, reason: 'this competition does not operate a video assistant referee' };
  if (!VAR_CATEGORIES.has(category))
    return { review: false, reason: 'not one of the four reviewable categories' };
  if (category === VAR_CATEGORY.RED_CARD && secondCaution)
    return { review: false,
             reason: 'a second caution is not reviewable, even though the player is sent off' };
  if (!clearAndObviousError && !seriousMissedIncident)
    return { review: false,
             reason: 'reviewable in principle, but there is no clear and obvious error and no '
                   + 'serious missed incident' };
  return { review: true, category,
           initiatedBy: OFFICIAL.REFEREE,
           finalDecisionBy: OFFICIAL.REFEREE,
           reason: seriousMissedIncident ? 'a serious missed incident'
                                         : 'a clear and obvious error' };
}

// Only the referee may start a review and only the referee takes the final decision. A model
// that lets the video official decide is not modelling this competition's referee.
function reviewOutcome({ initiatedBy, decidedBy, originalDecision, finalDecision }){
  const ok = initiatedBy === OFFICIAL.REFEREE && decidedBy === OFFICIAL.REFEREE;
  return { valid: ok, originalDecision, finalDecision,
           changed: ok && finalDecision !== originalDecision,
           reason: ok ? 'the referee started the review and took the decision'
                      : 'only the referee may start a review and only the referee decides' };
}

// ---------------------------------------------------------------------------------- Law 12
//
// CARDS, as opposed to restarts. laws.js already decides what the RESTART is; this decides what
// the player gets, which is a different question with a different answer for the same offence.
//
// The clause worth writing carefully is the one that replaced what used to be called the triple
// punishment. Where a player commits an offence against an opponent inside their OWN penalty
// area, denies an obvious goal-scoring opportunity, and a penalty kick is awarded, the offender
// is CAUTIONED rather than sent off - unless the offence was holding, pulling or pushing, or the
// offender had no possibility to play the ball, or it is an offence that is a red card wherever
// it happens. So the same tackle is a red card a metre outside the area and a yellow inside it,
// and any implementation that maps offence to card without looking at the location gets this
// wrong in both directions.

const CARD = { NONE: 'none', YELLOW: 'yellow', RED: 'red' };

// Offences the Law lists as a caution in their own right.
const CAUTIONABLE = new Set(['unsportingBehaviour', 'dissent', 'persistentOffences',
                             'delayingRestart', 'failingToRespectDistance',
                             'enteringOrLeavingWithoutPermission', 'enteringReviewArea',
                             'excessiveReviewSignal']);

// Offences the Law lists as a sending off wherever on the field they happen.
const RED_ANYWHERE = new Set(['seriousFoulPlay', 'violentConduct', 'bite', 'spit',
                              'offensiveLanguage', 'enteringVideoOperationRoom']);

// The three that keep a denied goal-scoring opportunity a red card even inside the area.
const NO_MITIGATION = new Set(['hold', 'pull', 'push']);

function disciplinaryAction({ offence, secondCaution = false,
                                     deniedGoalScoringOpportunity = false,
                                     stoppedPromisingAttack = false,
                                     handballDeniedGoal = false,
                                     offenderIsGoalkeeperInOwnArea = false,
                                     inOwnPenaltyArea = false, penaltyAwarded = false,
                                     couldPlayTheBall = true, profile }){
  const p = profile || {};

  if (secondCaution)
    return { card: CARD.RED, secondCaution: true,
             reason: 'a second caution in the same match' };

  if (RED_ANYWHERE.has(offence))
    return { card: CARD.RED, reason: 'a sending off offence wherever it happens' };

  // Handling to deny a goal or an obvious goal-scoring opportunity is a red card, except for a
  // goalkeeper inside their own penalty area.
  if (handballDeniedGoal) {
    if (offenderIsGoalkeeperInOwnArea)
      return { card: CARD.NONE,
               reason: 'a goalkeeper handling inside their own penalty area is not sent off '
                     + 'for it, whatever it denied' };
    return { card: CARD.RED,
             reason: 'denying a goal or an obvious goal-scoring opportunity by handling' };
  }

  if (deniedGoalScoringOpportunity) {
    const mitigated = inOwnPenaltyArea && penaltyAwarded
                   && !NO_MITIGATION.has(offence) && couldPlayTheBall;
    if (mitigated)
      return { card: CARD.YELLOW, mitigated: true,
               reason: 'an attempt to play the ball inside their own penalty area, with a '
                     + 'penalty kick awarded, so it is a caution and not a sending off' };
    return { card: CARD.RED,
             reason: inOwnPenaltyArea && penaltyAwarded
               ? (NO_MITIGATION.has(offence)
                   ? 'holding, pulling or pushing carries no mitigation inside the area'
                   : 'there was no possibility of playing the ball')
               : 'denying an obvious goal-scoring opportunity' };
  }

  if (stoppedPromisingAttack) {
    // The mirror of the clause above: inside their own area with a penalty given, stopping a
    // promising attack is not cautioned unless the offence would be cautioned anyway.
    if (inOwnPenaltyArea && penaltyAwarded && !CAUTIONABLE.has(offence))
      return { card: CARD.NONE, mitigated: true,
               reason: 'a penalty kick was awarded, so stopping a promising attack inside their '
                     + 'own area is not cautioned as well' };
    return { card: CARD.YELLOW, reason: 'stopping a promising attack' };
  }

  if (CAUTIONABLE.has(offence))
    return { card: CARD.YELLOW, reason: 'a cautionable offence' };

  // A temporary dismissal - a sin bin - exists in the Laws only for youth, veteran, disability
  // and grassroots football, and only where the competition adopts it. It is never assumed.
  if (offence === 'temporaryDismissal') {
    if (!isStated(p.temporaryDismissals))
      return { card: CARD.NONE, notStated: ['temporaryDismissals'],
               reason: 'NOT STATED in this profile: whether this competition uses temporary '
                     + 'dismissals. The Law permits them only in youth, veteran, disability '
                     + 'and grassroots football.' };
    if (!p.temporaryDismissals)
      return { card: CARD.NONE, reason: 'this competition does not use temporary dismissals' };
    return { card: CARD.YELLOW, temporaryDismissal: true,
             minutes: isStated(p.temporaryDismissalMinutes) ? p.temporaryDismissalMinutes : null,
             reason: 'a temporary dismissal, where the competition uses them' };
  }

  return { card: CARD.NONE,
           reason: 'NOT STATED: this offence carries no card in this model' };
}

// ---------------------------------------------------------------------------------- Law 10
//
// FINDING A WINNER.
//
// The match itself is simple: more goals wins, equal is a draw. Everything after that belongs to
// the competition, and the Law is unusually direct about it - away goals, extra time and kicks
// from the penalty mark are the ONLY permitted procedures for deciding a drawn match or tie.
// Whether any of them applies is a competition decision, so this file refuses to guess.

const RESULT = { HOME: 'home', AWAY: 'away', DRAW: 'draw',
                        EXTRA_TIME: 'extraTime', KICKS: 'kicksFromThePenaltyMark' };

function matchResult({ goalsHome, goalsAway }){
  if (goalsHome > goalsAway) return { result: RESULT.HOME, reason: 'the home team scored more' };
  if (goalsAway > goalsHome) return { result: RESULT.AWAY, reason: 'the away team scored more' };
  return { result: RESULT.DRAW, reason: 'the scores are equal, so the match is drawn' };
}

// A drawn match, resolved according to the competition. Everything this function does is driven
// by the profile; with a profile that states nothing, it returns NOT STATED rather than a
// winner, which is the correct answer to "who won" when nobody has said how to decide.
function decideDrawnMatch({ goalsHome, goalsAway, phase = PERIOD.SECOND_HALF, profile }){
  const p = profile || {};
  const base = matchResult({ goalsHome, goalsAway });
  if (base.result !== RESULT.DRAW) return base;

  if (!isStated(p.drawIsAllowed))
    return { result: null, notStated: ['drawIsAllowed'],
             reason: 'NOT STATED in this profile: whether a drawn match stands. That is in the '
                   + 'competition rules, not in the Laws.' };
  if (p.drawIsAllowed) return { result: RESULT.DRAW, reason: 'a drawn match stands' };

  if (phase === PERIOD.SECOND_HALF) {
    if (!isStated(p.extraTime))
      return { result: null, notStated: ['extraTime'],
               reason: 'NOT STATED in this profile: whether extra time is played' };
    if (p.extraTime) return { result: RESULT.EXTRA_TIME, reason: 'extra time is played' };
  }
  if (!isStated(p.kicksFromThePenaltyMark))
    return { result: null, notStated: ['kicksFromThePenaltyMark'],
             reason: 'NOT STATED in this profile: whether kicks from the penalty mark are taken' };
  if (p.kicksFromThePenaltyMark)
    return { result: RESULT.KICKS, reason: 'kicks from the penalty mark' };
  return { result: null,
           reason: 'NOT STATED: this profile forbids a draw but provides no way to decide it' };
}

// A two legged tie. The away goals rule is a competition decision and, since it was dropped by
// most competitions that used to apply it, defaulting it either way would be wrong. So it is
// NOT STATED unless the profile says.
function tieResult({ legs, profile }){
  const p = profile || {};
  // legs: [{ home: 'A', away: 'B', goalsHome, goalsAway }, ...] in the order they were played.
  let aggA = 0, aggB = 0, awayA = 0, awayB = 0;
  for (const leg of legs) {
    if (leg.home === 'A') { aggA += leg.goalsHome; aggB += leg.goalsAway; awayB += leg.goalsAway; }
    else                  { aggB += leg.goalsHome; aggA += leg.goalsAway; awayA += leg.goalsAway; }
  }
  if (aggA > aggB) return { winner: 'A', aggregate: [aggA, aggB], by: 'aggregate' };
  if (aggB > aggA) return { winner: 'B', aggregate: [aggA, aggB], by: 'aggregate' };

  if (!isStated(p.awayGoalsRule))
    return { winner: null, aggregate: [aggA, aggB], awayGoals: [awayA, awayB],
             notStated: ['awayGoalsRule'],
             reason: 'NOT STATED in this profile: whether away goals separate a level '
                   + 'aggregate. Most competitions that used the rule have dropped it, so '
                   + 'assuming either way would be inventing a regulation.' };
  if (p.awayGoalsRule) {
    if (awayA > awayB) return { winner: 'A', aggregate: [aggA, aggB], by: 'awayGoals' };
    if (awayB > awayA) return { winner: 'B', aggregate: [aggA, aggB], by: 'awayGoals' };
  }
  const next = decideDrawnMatch({ goalsHome: 0, goalsAway: 0, profile: p });
  return { winner: null, aggregate: [aggA, aggB], awayGoals: [awayA, awayB],
           next: next.result, notStated: next.notStated,
           reason: 'the aggregate is level' + (p.awayGoalsRule ? ' and so are the away goals' : '') };
}

// ---------------------------------------------------------------------------------- Law 10
//
// KICKS FROM THE PENALTY MARK. Written out in full because nearly every part of it is a rule
// that an obvious implementation gets wrong:
//
//   - both teams take FIVE kicks, alternately
//   - they stop early the moment one team has scored more than the other could reach even if it
//     took all of its remaining kicks. This is the rule that ends a shoot out at 3-0 after four
//     kicks each, and code that simply runs all ten misses it
//   - level after five each, it goes on in the same order until one team leads after an EQUAL
//     number of kicks. "Sudden death" is not sudden: the pair has to be completed
//   - only players on the field at the end of play, and those temporarily off it, are eligible
//   - if one team ends with more players than the other, it must REDUCE to the same number
//   - every eligible player must take a kick before any player takes a second
//
// The reduction and the coin toss are choices, not calculations - the model reports what has to
// be chosen and by whom, and refuses to choose. A model that picked the five takers itself would
// be inventing a manager.

function kicksReduceToEqual({ eligibleA, eligibleB }){
  const a = eligibleA.length, b = eligibleB.length;
  const n = Math.min(a, b);
  return {
    equalNumber: n,
    mustReduce: a === b ? null : (a > b ? 'A' : 'B'),
    removeCount: Math.abs(a - b),
    // DECISION of the team, not of this model: which players are left out is the team's choice
    // and is told to the referee. Nothing here picks them.
    chosenBy: a === b ? null : 'the team, which tells the referee which players are excluded',
    reason: a === b ? 'the teams already have equal numbers'
                    : 'the team with more players reduces to the same number',
  };
}

function kicksOpen({ firstTeam = 'A', eligibleA = [], eligibleB = [] }){
  return { firstTeam, eligible: { A: eligibleA.slice(), B: eligibleB.slice() },
           kicks: [], scored: { A: 0, B: 0 }, taken: { A: 0, B: 0 } };
}

function kicksTurn(state){
  const other = state.firstTeam === 'A' ? 'B' : 'A';
  return state.kicks.length % 2 === 0 ? state.firstTeam : other;
}

function kicksRecord(state, { team, playerId, scored }){
  const status = kicksStatus(state);
  if (status.decided)
    return { ok: false, state, reason: 'the kicks are already decided' };
  const due = kicksTurn(state);
  if (team !== due)
    return { ok: false, state, reason: 'it is ' + due + "'s turn to kick" };
  if (!state.eligible[team].includes(playerId))
    return { ok: false, state,
             reason: 'only a player on the field at the end of the match may take a kick' };
  // Every eligible player takes one before anybody takes a second, which also means the rule
  // applies again for the third round and so on.
  const byPlayer = state.kicks.filter(k => k.team === team && k.playerId === playerId).length;
  const round = Math.floor(state.taken[team] / state.eligible[team].length);
  if (byPlayer > round)
    return { ok: false, state,
             reason: 'every eligible player must take a kick before any player takes another' };

  const next = {
    ...state,
    kicks: state.kicks.concat([{ team, playerId, scored: !!scored }]),
    scored: { ...state.scored, [team]: state.scored[team] + (scored ? 1 : 0) },
    taken:  { ...state.taken,  [team]: state.taken[team] + 1 },
  };
  return { ok: true, state: next, status: kicksStatus(next) };
}

function kicksStatus(state){
  const { A, B } = state.scored;
  const tA = state.taken.A, tB = state.taken.B;
  const firstFive = tA < 5 || tB < 5;

  if (firstFive) {
    const leftA = Math.max(0, 5 - tA), leftB = Math.max(0, 5 - tB);
    if (A > B + leftB)
      return { decided: true, winner: 'A', scored: { A, B }, taken: { A: tA, B: tB },
               reason: 'B cannot reach A even by scoring all of its remaining kicks' };
    if (B > A + leftA)
      return { decided: true, winner: 'B', scored: { A, B }, taken: { A: tA, B: tB },
               reason: 'A cannot reach B even by scoring all of its remaining kicks' };
    return { decided: false, scored: { A, B }, taken: { A: tA, B: tB },
             reason: 'inside the first five, and still reachable' };
  }
  // Beyond five each. A lead only counts after an equal number of kicks.
  if (tA !== tB)
    return { decided: false, scored: { A, B }, taken: { A: tA, B: tB },
             reason: 'the pair of kicks is not complete' };
  if (A !== B)
    return { decided: true, winner: A > B ? 'A' : 'B', scored: { A, B }, taken: { A: tA, B: tB },
             reason: 'one team leads after an equal number of kicks' };
  return { decided: false, scored: { A, B }, taken: { A: tA, B: tB },
           reason: 'level after an equal number of kicks, so they continue' };
}

// Where everyone stands. The kicker's own goalkeeper waits on the field, outside the penalty
// area, on the goal line where it meets the penalty area boundary. Every other player is in the
// centre circle.
function kicksPositions({ goalSide = 1, pitch = PITCH }){
  return {
    mark: { x: goalSide * (pitch.halfLength - pitch.penaltyMarkFromGoal), z: 0 },
    defendingKeeperOn: { x: goalSide * pitch.halfLength,
                         zRange: [-pitch.goalHalfWidth, pitch.goalHalfWidth] },
    kickersKeeperAt: { x: goalSide * pitch.halfLength, z: pitch.penaltyAreaHalfWidth },
    everyoneElse: { x: 0, z: 0, inCentreCircle: true },
    // NOT STATED here: which goal is used. The Law has the referee toss a coin for it, and a
    // coin is not a calculation, so the caller supplies goalSide.
    goalChosenBy: 'the referee tosses a coin, unless the ground or safety decides it',
  };
}

const MATCH_VERSION = 'week 2 - Laws 3, 5, 6, 7, 10 and the cards of Law 12';

return {PERIOD:PERIOD,DURATION:DURATION,ADDED_TIME_REASONS:ADDED_TIME_REASONS,addedTime:addedTime,periodEnded:periodEnded,TEAM:TEAM,teamCanPlay:teamCanPlay,NOT_STATED:NOT_STATED,isStated:isStated,substitutionCheck:substitutionCheck,goalkeeperChange:goalkeeperChange,OFFICIAL:OFFICIAL,OFFICIAL_DUTIES:OFFICIAL_DUTIES,DECISIONS_ARE_THE_REFEREES:DECISIONS_ARE_THE_REFEREES,mayChangeRestart:mayChangeRestart,mayStillSanction:mayStillSanction,VAR_CATEGORY:VAR_CATEGORY,varMayReview:varMayReview,reviewOutcome:reviewOutcome,CARD:CARD,disciplinaryAction:disciplinaryAction,RESULT:RESULT,matchResult:matchResult,decideDrawnMatch:decideDrawnMatch,tieResult:tieResult,kicksReduceToEqual:kicksReduceToEqual,kicksOpen:kicksOpen,kicksTurn:kicksTurn,kicksRecord:kicksRecord,kicksStatus:kicksStatus,kicksPositions:kicksPositions,MATCH_VERSION:MATCH_VERSION};
})();
window.PROF=(function(){
// ==============================================================================================
// profiles.js - the competition profile layer
// Copyright (c) AI2ORBIT Co. 2026
//
// THE POINT OF THIS FILE, IN ONE PARAGRAPH
//
// UEFA, FIFA, the English, Spanish, German, Swedish, Belgian, French, Canadian, Mexican, Latin
// American, Copa and US competitions all play under the SAME Laws of the Game. There is one set,
// published by the IFAB, and none of those bodies writes its own. What differs between them is
// not the Laws, it is the COMPETITION REGULATIONS - how many substitutes may be named, whether
// there is a video assistant referee, what happens when a knockout tie is level. The Laws
// themselves say so, over and over: "competition rules must state...".
//
// So the right seam is not one rules engine per competition. It is one rules engine, and a thin
// profile of the fields the Laws hand to the competition. That is this file. Adding a
// competition adds a profile; it never forks a rule. laws.js and match.js do not know this file
// exists, and nothing here is imported by them.
//
// WHY MOST OF THESE PROFILES ARE MOSTLY EMPTY, AND WHY THAT IS THE HONEST ANSWER
//
// A competition's regulations are a published document that changes every season. I do not have
// those fourteen documents, so I have not typed numbers into them from memory. Every field a
// competition owns and that I cannot source is marked NOT STATED, and reading one gives you the
// words NOT STATED rather than a plausible number.
//
// This is deliberate and it is the most useful thing in the file. A profile that quietly
// defaulted "five substitutes" would be wrong for some of these competitions and nobody would
// ever find out, because the wrong answer looks exactly like the right one. A profile that says
// NOT STATED produces a printable checklist - see `report()` - of precisely which fields have to
// be filled in per competition, and nothing more. Fill one in and it is used everywhere at once.
//
// What IS stated here is what the Laws state, plus what is true by definition of the kind of
// match being played: a league fixture that ends level is a draw, because that is what a league
// fixture means. Nothing else has been assumed.
// ==============================================================================================

var {PITCH, LAWS} = window.LAW;
var {NOT_STATED, isStated, DURATION, TEAM} = window.MATCH;
// ---------------------------------------------------------------------------------- the fields
//
// Every field this layer knows about, with the one thing that matters most beside it: WHO OWNS
// IT. A field owned by the Law cannot be changed by a competition and an override of one is
// refused. A field owned by the competition has no defensible default at all, which is exactly
// why it is here.
//
// `lawRange` is present where the Law fixes limits the competition must choose inside. Law 1
// gives the pitch a range; Law 3 caps the substitutes that may be named at fifteen and the
// substitution opportunities at three. An override outside those limits is refused rather than
// clamped, because silently clamping a value produces a match played under rules nobody wrote.

const OWNER = { LAW: 'law', COMPETITION: 'competition' };

const FIELDS = {
  // ---- Law 1, the field of play. The competition chooses inside the Law's range.
  pitchLengthM:  { owner: OWNER.COMPETITION, lawRange: [90, 120],
                   note: 'Law 1 range. International matches are 100-110 m.' },
  pitchWidthM:   { owner: OWNER.COMPETITION, lawRange: [45, 90],
                   note: 'Law 1 range. International matches are 64-75 m.' },

  // ---- Law 3, the players.
  minimumPlayers:          { owner: OWNER.LAW, note: 'seven, and the competition cannot move it' },
  namedSubstitutes:        { owner: OWNER.COMPETITION, lawRange: [3, 15],
                             note: 'Law 3: the competition must state a number in this range' },
  substitutionsAllowed:    { owner: OWNER.COMPETITION, lawRange: [0, 5],
                             note: 'up to five, except return substitutes in the football the '
                                 + 'Law allows them in' },
  substitutionOpportunities: { owner: OWNER.COMPETITION, lawRange: [0, 3],
                             note: 'Law 3 caps these at three, not counting the intervals' },
  returnSubstitutes:       { owner: OWNER.COMPETITION,
                             note: 'the Law permits these only in youth, veteran, disability '
                                 + 'and grassroots football' },
  extraTimeExtraSubstitution: { owner: OWNER.COMPETITION },
  extraTimeExtraOpportunity:  { owner: OWNER.COMPETITION },
  concussionSubstitutes:   { owner: OWNER.COMPETITION,
                             note: 'permanent, additional, and only where the competition is '
                                 + 'approved to operate the protocol' },

  // ---- Law 6 and the technology, every piece of which is a competition decision.
  videoAssistantReferee:   { owner: OWNER.COMPETITION },
  goalLineTechnology:      { owner: OWNER.COMPETITION },
  semiAutomatedOffside:    { owner: OWNER.COMPETITION },
  levelToleranceM:         { owner: OWNER.COMPETITION,
                             note: 'the Law states no tolerance at all; a competition running '
                                 + 'semi automated offside publishes its own' },
  fourthOfficial:          { owner: OWNER.COMPETITION },
  reserveAssistantReferee: { owner: OWNER.COMPETITION },

  // ---- Law 7, the clock.
  halfMinutes:             { owner: OWNER.COMPETITION, lawRange: [1, 45],
                             note: 'may only be reduced, by agreement before the match' },
  halfTimeIntervalMinutes: { owner: OWNER.COMPETITION, lawRange: [0, 15] },
  drinksBreaks:            { owner: OWNER.COMPETITION },
  coolingBreaks:           { owner: OWNER.COMPETITION },

  // ---- Law 10, finding a winner. None of this is in the Laws.
  drawIsAllowed:           { owner: OWNER.COMPETITION },
  extraTime:               { owner: OWNER.COMPETITION },
  kicksFromThePenaltyMark: { owner: OWNER.COMPETITION },
  awayGoalsRule:           { owner: OWNER.COMPETITION,
                             note: 'most competitions that used it have dropped it, so neither '
                                 + 'answer is a safe default' },
  replayIfDrawn:           { owner: OWNER.COMPETITION },

  // ---- Law 12, discipline beyond the card itself.
  temporaryDismissals:     { owner: OWNER.COMPETITION,
                             note: 'the Law permits sin bins only in youth, veteran, disability '
                                 + 'and grassroots football' },
  temporaryDismissalMinutes: { owner: OWNER.COMPETITION },
  cautionsBeforeSuspension:  { owner: OWNER.COMPETITION,
                             note: 'entirely a competition matter; the Laws say nothing' },
};

// ---------------------------------------------------------------------------------- the base
//
// The IFAB base. Only what the Laws themselves state. Everything a competition owns starts here
// as NOT STATED, and that is the point: this object is the list of questions, not the answers.

const BASE = Object.freeze({
  id: 'ifab',
  name: 'The Laws of the Game',
  authority: 'IFAB',
  note: 'the Laws every competition below plays under, unchanged',

  minimumPlayers: TEAM.minimumToPlay,
  halfMinutes: DURATION.halfMinutes,
  halfTimeIntervalMinutes: DURATION.halfTimeIntervalMaxMinutes,
  pitchLengthM: PITCH.halfLength * 2,
  pitchWidthM: PITCH.halfWidth * 2,

  // The Law's own default: a substituted player takes no further part.
  returnSubstitutes: false,
  // Sin bins exist in the Laws only for the football listed against the field above.
  temporaryDismissals: false,
  // Zero is the Law. laws.js already marks this a DECISION where it is consumed.
  levelToleranceM: LAWS.levelToleranceM,
  // The Law caps these; it does not set them. The cap is the honest value for the base.
  substitutionOpportunities: 3,

  namedSubstitutes: NOT_STATED,
  substitutionsAllowed: NOT_STATED,
  extraTimeExtraSubstitution: NOT_STATED,
  extraTimeExtraOpportunity: NOT_STATED,
  concussionSubstitutes: NOT_STATED,
  videoAssistantReferee: NOT_STATED,
  goalLineTechnology: NOT_STATED,
  semiAutomatedOffside: NOT_STATED,
  fourthOfficial: NOT_STATED,
  reserveAssistantReferee: NOT_STATED,
  drinksBreaks: NOT_STATED,
  coolingBreaks: NOT_STATED,
  drawIsAllowed: NOT_STATED,
  extraTime: NOT_STATED,
  kicksFromThePenaltyMark: NOT_STATED,
  awayGoalsRule: NOT_STATED,
  replayIfDrawn: NOT_STATED,
  temporaryDismissalMinutes: NOT_STATED,
  cautionsBeforeSuspension: NOT_STATED,
});

// ---------------------------------------------------------------------------------- contexts
//
// The KIND of match, which is a separate axis from the competition running it. The same
// competition plays league fixtures and knockout ties under different resolutions of a draw, so
// putting "extra time" on the competition would be wrong for half its matches.
//
// Only the things that are true BY DEFINITION of the kind of match are stated. A league fixture
// that finishes level is a draw - that is what a league fixture is. What a drawn knockout tie
// does next is a regulation and stays NOT STATED, because competitions genuinely differ: some
// play extra time, some go straight to kicks, some still replay.

const CONTEXT = {
  leagueFixture: {
    id: 'leagueFixture',
    name: 'a league fixture',
    drawIsAllowed: true,
    extraTime: false,
    kicksFromThePenaltyMark: false,
    awayGoalsRule: false,
    replayIfDrawn: false,
    why: 'a league fixture that ends level is a draw, by definition of a league',
  },
  knockoutSingleLeg: {
    id: 'knockoutSingleLeg',
    name: 'a single leg knockout tie',
    drawIsAllowed: false,
    awayGoalsRule: false,
    why: 'a knockout tie must produce a winner; HOW is a regulation and is left NOT STATED',
  },
  knockoutTwoLeg: {
    id: 'knockoutTwoLeg',
    name: 'a two legged knockout tie',
    drawIsAllowed: false,
    why: 'decided on aggregate; whether away goals separate a level aggregate is NOT STATED',
  },
  // Two fully specified shapes, offered so a competition can point at one the day somebody
  // confirms which it uses. They are shapes, not any competition's published regulations.
  knockoutExtraTimeThenKicks: {
    id: 'knockoutExtraTimeThenKicks',
    name: 'a knockout tie: extra time, then kicks from the penalty mark',
    drawIsAllowed: false, extraTime: true, kicksFromThePenaltyMark: true,
    awayGoalsRule: false, replayIfDrawn: false,
    extraTimeExtraSubstitution: true, extraTimeExtraOpportunity: true,
    why: 'a shape a competition may select, not a claim about any particular competition',
  },
  knockoutKicksOnly: {
    id: 'knockoutKicksOnly',
    name: 'a knockout tie: straight to kicks from the penalty mark',
    drawIsAllowed: false, extraTime: false, kicksFromThePenaltyMark: true,
    awayGoalsRule: false, replayIfDrawn: false,
    why: 'a shape a competition may select, not a claim about any particular competition',
  },
};

// ---------------------------------------------------------------------------------- the list
//
// The thirteen variants asked for, plus the base. Each states its name, the body that runs it
// and the confederation it sits in - facts about the competition, not regulations - and then
// states that it plays under the IFAB Laws, which is the fact that makes this whole layer
// possible.
//
// Every regulation field is inherited as NOT STATED. `report()` prints the list per competition.

const comp = (id, name, body, confederation, extra = {}) =>
  Object.freeze({ id, name, body, confederation, lawsPublishedBy: 'IFAB', ...extra });

const COMPETITIONS = Object.freeze({
  ifab:          comp('ifab', 'The Laws of the Game', 'IFAB', 'worldwide',
                      { note: 'the base every other profile inherits' }),
  fifa:          comp('fifa', 'FIFA competitions', 'FIFA', 'worldwide',
                      { note: 'international matches: Law 1 narrows the pitch to 100-110 m '
                            + 'by 64-75 m, which is the one regulation the Law itself sets',
                        pitchLengthRangeM: [100, 110], pitchWidthRangeM: [64, 75] }),
  uefa:          comp('uefa', 'UEFA competitions', 'UEFA', 'Europe'),
  english:       comp('english', 'English football', 'The Football Association', 'UEFA'),
  spanish:       comp('spanish', 'Spanish football', 'Real Federacion Espanola de Futbol', 'UEFA'),
  german:        comp('german', 'German football', 'Deutscher Fussball-Bund', 'UEFA'),
  swedish:       comp('swedish', 'Swedish football', 'Svenska Fotbollforbundet', 'UEFA'),
  belgian:       comp('belgian', 'Belgian football', 'Royal Belgian Football Association', 'UEFA'),
  french:        comp('french', 'French football', 'Federation Francaise de Football', 'UEFA'),
  canadian:      comp('canadian', 'Canadian football', 'Canada Soccer', 'CONCACAF'),
  mexican:       comp('mexican', 'Mexican football', 'Federacion Mexicana de Futbol', 'CONCACAF'),
  us:            comp('us', 'United States football', 'United States Soccer Federation',
                      'CONCACAF'),
  latinAmerican: comp('latinAmerican', 'South American club football', 'CONMEBOL',
                      'CONMEBOL'),
  copa:          comp('copa', 'Copa America', 'CONMEBOL', 'CONMEBOL'),
});

// ---------------------------------------------------------------------------------- resolving
//
// BASE, then the context, then the competition, then whatever the caller supplies. Later beats
// earlier, and a NOT STATED value never overwrites a stated one - a profile that says nothing
// must not erase a fact, only fail to add one.
//
// WHY THE COMPETITION BEATS THE CONTEXT, since the opposite order looks just as reasonable.
//
// The context supplies what is true by DEFINITION of the kind of match, which makes it a
// default rather than a regulation. A competition is entitled to contradict that default and
// some have: a league whose drawn fixtures were settled by a shoot out was still a league. So
// the competition's own regulations win, and the caller's overrides win over those, which is
// the escape hatch for a single match that differs from both.
//
// This ordering is not obvious from reading the code, so it has its own check in the suite -
// swapping these two lines changed no answer at all until that check existed.

function layer(into, from){
  for (const [k, v] of Object.entries(from || {})) {
    if (!(k in FIELDS)) continue;              // names, notes and prose are not fields
    if (!isStated(v)) continue;                // NOT STATED adds nothing; it does not erase
    into[k] = v;
  }
  return into;
}

// An override is checked before it is applied, not after. Three ways it is refused: a field
// nobody has heard of, a field the Law owns, and a value outside the range the Law allows.
function validateOverrides(overrides, competition){
  const errors = [];
  for (const [k, v] of Object.entries(overrides || {})) {
    const f = FIELDS[k];
    if (!f) { errors.push(k + ': no such field'); continue; }
    if (f.owner === OWNER.LAW) {
      errors.push(k + ': owned by the Laws, not by a competition, so it cannot be overridden');
      continue;
    }
    if (!isStated(v)) continue;
    let range = f.lawRange;
    // FIFA's international matches carry a narrower pitch range, and it is the Law that
    // narrows it, so it is enforced here rather than left as a comment.
    if (competition && k === 'pitchLengthM' && competition.pitchLengthRangeM)
      range = competition.pitchLengthRangeM;
    if (competition && k === 'pitchWidthM' && competition.pitchWidthRangeM)
      range = competition.pitchWidthRangeM;
    if (range && typeof v === 'number' && (v < range[0] || v > range[1]))
      errors.push(k + ': ' + v + ' is outside the range the Law allows, ' +
                  range[0] + ' to ' + range[1]);
  }
  return { ok: errors.length === 0, errors };
}

function resolve({ competition = 'ifab', context = null, overrides = null } = {}){
  const c = typeof competition === 'string' ? COMPETITIONS[competition] : competition;
  if (!c) throw new Error('no such competition profile: ' + competition);
  const ctx = context == null ? null
            : (typeof context === 'string' ? CONTEXT[context] : context);
  if (context != null && !ctx) throw new Error('no such match context: ' + context);

  const check = validateOverrides(overrides, c);
  if (!check.ok) throw new Error('the overrides are not usable: ' + check.errors.join('; '));

  const out = {};
  for (const [k, v] of Object.entries(BASE)) if (k in FIELDS) out[k] = v;
  layer(out, ctx);
  layer(out, c);
  layer(out, overrides);

  const unstated = Object.keys(FIELDS).filter(k => !isStated(out[k])).sort();

  // The half the rest of the engine consumes. `laws` is shaped exactly like LAWS in laws.js so
  // it drops straight into the week 1 functions - which is what "the competitions differ
  // without forking the rules" has to mean in code rather than in a sentence.
  const laws = { ...LAWS, levelToleranceM: isStated(out.levelToleranceM)
                                             ? out.levelToleranceM : LAWS.levelToleranceM };
  const pitch = { ...PITCH,
                  halfLength: isStated(out.pitchLengthM) ? out.pitchLengthM / 2 : PITCH.halfLength,
                  halfWidth:  isStated(out.pitchWidthM)  ? out.pitchWidthM / 2  : PITCH.halfWidth };

  return {
    id: c.id,
    name: c.name,
    body: c.body,
    confederation: c.confederation,
    lawsPublishedBy: 'IFAB',
    context: ctx ? ctx.id : null,
    contextName: ctx ? ctx.name : null,
    ...out,
    laws, pitch,
    unstated,
    stated: Object.keys(FIELDS).filter(k => isStated(out[k])).sort(),
  };
}

// Reading a NOT STATED field by accident is the failure this whole file exists to prevent, and
// a comment does not prevent it. `strict()` wraps a resolved profile so that reading one throws
// with the field's name in the message. Use it in anything that must not run on a guess.
function strict(resolved){
  return new Proxy(resolved, {
    get(target, key){
      const v = target[key];
      if (typeof key === 'string' && key in FIELDS && !isStated(v))
        throw new Error('"' + key + '" is NOT STATED for the ' + target.name + ' profile. ' +
                        (FIELDS[key].note ? FIELDS[key].note + '. ' : '') +
                        'The Laws leave it to the competition, so it has to come from that ' +
                        "competition's published regulations rather than from a default.");
      return v;
    },
  });
}

// ---------------------------------------------------------------------------------- the report
//
// The printable checklist. This is the artefact the profile layer is actually FOR: hand it to
// whoever holds a competition's regulations and every line is one thing to fill in.

// 64 columns, and third person throughout, which is how every report on this project is set.
const RPT_WIDTH = 64;
function wrapLine(text, indent){
  const pad = ' '.repeat(indent);
  const out = [];
  let line = '';
  for (const word of text.split(/\s+/)) {
    if (!line) { line = word; continue; }
    if ((line + ' ' + word).length + indent > RPT_WIDTH) { out.push(pad + line); line = word; }
    else line += ' ' + word;
  }
  if (line) out.push(pad + line);
  return out;
}

function report(competitionId = null, contextId = null){
  const ids = competitionId ? [competitionId] : Object.keys(COMPETITIONS);
  const lines = [];
  for (const id of ids) {
    const r = resolve({ competition: id, context: contextId });
    lines.push(...wrapLine(r.name + '  (' + r.body + ', ' + r.confederation + ')' +
                           (r.contextName ? ' - ' + r.contextName : ''), 0));
    lines.push(...wrapLine('plays under: the Laws of the Game, published by IFAB, '
                           + 'unchanged', 2));
    lines.push('  stated here: ' + r.stated.length + ' fields');
    if (r.unstated.length === 0) {
      lines.push('  to be filled in from the published regulations: none');
    } else {
      lines.push('  to be filled in from the published regulations, ' +
                 r.unstated.length + ' fields:');
      for (const k of r.unstated) {
        lines.push('    ' + k);
        if (FIELDS[k].note) lines.push(...wrapLine(FIELDS[k].note, 6));
      }
    }
    lines.push('');
  }
  return lines.join('\n');
}

const PROFILES_VERSION =
  'week 2 - the competition profile layer, ' + Object.keys(COMPETITIONS).length + ' profiles';

return {OWNER:OWNER,FIELDS:FIELDS,BASE:BASE,CONTEXT:CONTEXT,COMPETITIONS:COMPETITIONS,validateOverrides:validateOverrides,resolve:resolve,strict:strict,report:report,PROFILES_VERSION:PROFILES_VERSION,NOT_STATED:NOT_STATED,isStated:isStated};
})();
